#!/bin/bash
jhhudrgir hgierigheei rgiei hghg g eiurhghieh righeirgeoiorjgiueurgi herihg eeigii ie ei ri euhrgri  ig eirigei g ihrgri.
 eiugeihgie gieh ighieuhgiehg eiuuhrgie iuhg ieuehgie iuuhg eieuh ge gue ego eiuirg oeurgiueoguhgeiuhrgoiegugu e _g e g iih erogh riigieurhgoeojgh goh eoigjeohriueeh rogjj ei ughorijgj uruhtogi triu hoitrui.
/root/alx-system_engineering-devops/0x00-shell_basics
